// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvtwkzjxcatcjozoyesx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2dHdremp4Y2F0Y2pvem95ZXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjYwOTgsImV4cCI6MjA2MDU0MjA5OH0.zafrU_JMDX6I9nfUrIonq82kx8e_YoJszOWCrluW2dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);